# Grafana Configuration
grafana:
  adminPassword: "newp@ssw0rd"
  persistence:
    enabled: true
    storageClassName: local-path
    size: 3Gi
  service:
    type: NodePort
    nodePort: 30001
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      tech-trends-dashboard:
        json: |
          {
            "dashboard": {
              "title": "Observability Dashboard",
              "panels": []
            }
          }

# Prometheus Configuration
prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi


# Node Exporter
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Service Monitor for your application
# additionalScrapeConfigs:
#   - job_name: 'techtrends-app'
#     static_configs:
#       - targets: ['techtrends-app-service:5000']
#     metrics_path: /metrics
#     scrape_interval: 30s